# Development Dockerfile
FROM node:22-alpine

# Install dependencies
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy Prisma schema
COPY prisma/schema.prisma ./prisma/

# Generate Prisma client
RUN npx prisma generate


# Copy the rest of the project
COPY . .

# Expose the default Next.js port
EXPOSE 3000


# Start the development server
CMD ["npm", "run", "dev"]